{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/anas7abdelghany/Build-Your-Own-PyCaret/blob/main/Build_Your_Own_PyCaret.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "8jSvFgigssUQ",
        "outputId": "b8fdfb24-3c48-45a2-d524-f902947e4d58"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Collecting streamlit\n",
            "  Using cached streamlit-1.34.0-py2.py3-none-any.whl (8.5 MB)\n",
            "Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.2.2)\n",
            "Requirement already satisfied: blinker<2,>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit) (1.4)\n",
            "Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.3.3)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.1.7)\n",
            "Requirement already satisfied: numpy<2,>=1.19.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.25.2)\n",
            "Requirement already satisfied: packaging<25,>=16.8 in /usr/local/lib/python3.10/dist-packages (from streamlit) (24.0)\n",
            "Requirement already satisfied: pandas<3,>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.0.3)\n",
            "Requirement already satisfied: pillow<11,>=7.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (9.4.0)\n",
            "Requirement already satisfied: protobuf<5,>=3.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.20.3)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (14.0.2)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.31.0)\n",
            "Requirement already satisfied: rich<14,>=10.14.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (13.7.1)\n",
            "Requirement already satisfied: tenacity<9,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.2.3)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.11.0)\n",
            "Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)\n",
            "  Using cached GitPython-3.1.43-py3-none-any.whl (207 kB)\n",
            "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
            "  Using cached pydeck-0.9.0-py2.py3-none-any.whl (6.9 MB)\n",
            "Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.3.3)\n",
            "Collecting watchdog>=2.1.5 (from streamlit)\n",
            "  Using cached watchdog-4.0.0-py3-none-manylinux2014_x86_64.whl (82 kB)\n",
            "Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.4)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (3.1.3)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (4.19.2)\n",
            "Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.12.1)\n",
            "Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
            "  Using cached gitdb-4.0.11-py3-none-any.whl (62 kB)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2.8.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2023.4)\n",
            "Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.7)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2.0.7)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2024.2.2)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (2.16.1)\n",
            "Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
            "  Using cached smmap-5.0.1-py3-none-any.whl (24 kB)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.5)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.2.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.12.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.35.0)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.18.0)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)\n",
            "Installing collected packages: watchdog, smmap, pydeck, gitdb, gitpython, streamlit\n",
            "Successfully installed gitdb-4.0.11 gitpython-3.1.43 pydeck-0.9.0 smmap-5.0.1 streamlit-1.34.0 watchdog-4.0.0\n"
          ]
        }
      ],
      "source": [
        "!pip install streamlit"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "IOfntB5ES64l",
        "outputId": "7a0cca12-c8f5-4c1b-c800-df2e46f66ac7"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Collecting pycaret\n",
            "  Downloading pycaret-3.3.2-py3-none-any.whl (486 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m486.1/486.1 kB\u001b[0m \u001b[31m6.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: ipython>=5.5.0 in /usr/local/lib/python3.10/dist-packages (from pycaret) (7.34.0)\n",
            "Requirement already satisfied: ipywidgets>=7.6.5 in /usr/local/lib/python3.10/dist-packages (from pycaret) (7.7.1)\n",
            "Requirement already satisfied: tqdm>=4.62.0 in /usr/local/lib/python3.10/dist-packages (from pycaret) (4.66.2)\n",
            "Requirement already satisfied: numpy<1.27,>=1.21 in /usr/local/lib/python3.10/dist-packages (from pycaret) (1.25.2)\n",
            "Requirement already satisfied: pandas<2.2.0 in /usr/local/lib/python3.10/dist-packages (from pycaret) (2.0.3)\n",
            "Requirement already satisfied: jinja2>=3 in /usr/local/lib/python3.10/dist-packages (from pycaret) (3.1.3)\n",
            "Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in /usr/local/lib/python3.10/dist-packages (from pycaret) (1.11.4)\n",
            "Collecting joblib<1.4,>=1.2.0 (from pycaret)\n",
            "  Downloading joblib-1.3.2-py3-none-any.whl (302 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m302.2/302.2 kB\u001b[0m \u001b[31m11.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting scikit-learn>1.4.0 (from pycaret)\n",
            "  Downloading scikit_learn-1.4.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m12.1/12.1 MB\u001b[0m \u001b[31m19.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting pyod>=1.1.3 (from pycaret)\n",
            "  Downloading pyod-1.1.3.tar.gz (160 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m160.5/160.5 kB\u001b[0m \u001b[31m18.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Collecting imbalanced-learn>=0.12.0 (from pycaret)\n",
            "  Downloading imbalanced_learn-0.12.2-py3-none-any.whl (257 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m258.0/258.0 kB\u001b[0m \u001b[31m24.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting category-encoders>=2.4.0 (from pycaret)\n",
            "  Downloading category_encoders-2.6.3-py2.py3-none-any.whl (81 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m81.9/81.9 kB\u001b[0m \u001b[31m10.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: lightgbm>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from pycaret) (4.1.0)\n",
            "Requirement already satisfied: numba>=0.55.0 in /usr/local/lib/python3.10/dist-packages (from pycaret) (0.58.1)\n",
            "Requirement already satisfied: requests>=2.27.1 in /usr/local/lib/python3.10/dist-packages (from pycaret) (2.31.0)\n",
            "Requirement already satisfied: psutil>=5.9.0 in /usr/local/lib/python3.10/dist-packages (from pycaret) (5.9.5)\n",
            "Requirement already satisfied: markupsafe>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from pycaret) (2.1.5)\n",
            "Requirement already satisfied: importlib-metadata>=4.12.0 in /usr/local/lib/python3.10/dist-packages (from pycaret) (7.1.0)\n",
            "Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pycaret) (5.10.4)\n",
            "Requirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from pycaret) (2.2.1)\n",
            "Collecting deprecation>=2.1.0 (from pycaret)\n",
            "  Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)\n",
            "Collecting xxhash (from pycaret)\n",
            "  Downloading xxhash-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m194.1/194.1 kB\u001b[0m \u001b[31m19.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: matplotlib<3.8.0 in /usr/local/lib/python3.10/dist-packages (from pycaret) (3.7.1)\n",
            "Collecting scikit-plot>=0.3.7 (from pycaret)\n",
            "  Downloading scikit_plot-0.3.7-py3-none-any.whl (33 kB)\n",
            "Requirement already satisfied: yellowbrick>=1.4 in /usr/local/lib/python3.10/dist-packages (from pycaret) (1.5)\n",
            "Requirement already satisfied: plotly>=5.14.0 in /usr/local/lib/python3.10/dist-packages (from pycaret) (5.15.0)\n",
            "Collecting kaleido>=0.2.1 (from pycaret)\n",
            "  Downloading kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl (79.9 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m79.9/79.9 MB\u001b[0m \u001b[31m6.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting schemdraw==0.15 (from pycaret)\n",
            "  Downloading schemdraw-0.15-py3-none-any.whl (106 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m106.8/106.8 kB\u001b[0m \u001b[31m11.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting plotly-resampler>=0.8.3.1 (from pycaret)\n",
            "  Downloading plotly_resampler-0.10.0-py3-none-any.whl (80 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m80.7/80.7 kB\u001b[0m \u001b[31m9.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: statsmodels>=0.12.1 in /usr/local/lib/python3.10/dist-packages (from pycaret) (0.14.2)\n",
            "Collecting sktime==0.26.0 (from pycaret)\n",
            "  Downloading sktime-0.26.0-py3-none-any.whl (21.8 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m21.8/21.8 MB\u001b[0m \u001b[31m39.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting tbats>=1.1.3 (from pycaret)\n",
            "  Downloading tbats-1.1.3-py3-none-any.whl (44 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m44.0/44.0 kB\u001b[0m \u001b[31m4.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting pmdarima>=2.0.4 (from pycaret)\n",
            "  Downloading pmdarima-2.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl (2.1 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.1/2.1 MB\u001b[0m \u001b[31m49.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting wurlitzer (from pycaret)\n",
            "  Downloading wurlitzer-3.1.0-py3-none-any.whl (8.4 kB)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from sktime==0.26.0->pycaret) (24.0)\n",
            "Collecting scikit-base<0.8.0 (from sktime==0.26.0->pycaret)\n",
            "  Downloading scikit_base-0.7.7-py3-none-any.whl (129 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m129.9/129.9 kB\u001b[0m \u001b[31m16.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category-encoders>=2.4.0->pycaret) (0.5.6)\n",
            "Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn>=0.12.0->pycaret) (3.5.0)\n",
            "Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata>=4.12.0->pycaret) (3.18.1)\n",
            "Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->pycaret) (67.7.2)\n",
            "Collecting jedi>=0.16 (from ipython>=5.5.0->pycaret)\n",
            "  Downloading jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.6/1.6 MB\u001b[0m \u001b[31m66.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->pycaret) (4.4.2)\n",
            "Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->pycaret) (0.7.5)\n",
            "Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->pycaret) (5.7.1)\n",
            "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->pycaret) (3.0.43)\n",
            "Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->pycaret) (2.16.1)\n",
            "Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->pycaret) (0.2.0)\n",
            "Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->pycaret) (0.1.7)\n",
            "Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.5.0->pycaret) (4.9.0)\n",
            "Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets>=7.6.5->pycaret) (5.5.6)\n",
            "Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets>=7.6.5->pycaret) (0.2.0)\n",
            "Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets>=7.6.5->pycaret) (3.6.6)\n",
            "Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets>=7.6.5->pycaret) (3.0.10)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.8.0->pycaret) (1.2.1)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.8.0->pycaret) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.8.0->pycaret) (4.51.0)\n",
            "Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.8.0->pycaret) (1.4.5)\n",
            "Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.8.0->pycaret) (9.4.0)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.8.0->pycaret) (3.1.2)\n",
            "Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.8.0->pycaret) (2.8.2)\n",
            "Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.10/dist-packages (from nbformat>=4.2.0->pycaret) (2.19.1)\n",
            "Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.10/dist-packages (from nbformat>=4.2.0->pycaret) (4.19.2)\n",
            "Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.10/dist-packages (from nbformat>=4.2.0->pycaret) (5.7.2)\n",
            "Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>=0.55.0->pycaret) (0.41.1)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.2.0->pycaret) (2023.4)\n",
            "Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.2.0->pycaret) (2024.1)\n",
            "Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=5.14.0->pycaret) (8.2.3)\n",
            "Collecting dash>=2.9.0 (from plotly-resampler>=0.8.3.1->pycaret)\n",
            "  Downloading dash-2.17.0-py3-none-any.whl (7.5 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m7.5/7.5 MB\u001b[0m \u001b[31m77.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting orjson<4.0.0,>=3.8.0 (from plotly-resampler>=0.8.3.1->pycaret)\n",
            "  Downloading orjson-3.10.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m142.5/142.5 kB\u001b[0m \u001b[31m17.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting tsdownsample>=0.1.3 (from plotly-resampler>=0.8.3.1->pycaret)\n",
            "  Downloading tsdownsample-0.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.1/2.1 MB\u001b[0m \u001b[31m75.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in /usr/local/lib/python3.10/dist-packages (from pmdarima>=2.0.4->pycaret) (3.0.10)\n",
            "Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from pmdarima>=2.0.4->pycaret) (2.0.7)\n",
            "Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from pyod>=1.1.3->pycaret) (1.16.0)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->pycaret) (3.3.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->pycaret) (3.7)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->pycaret) (2024.2.2)\n",
            "Requirement already satisfied: Flask<3.1,>=1.0.4 in /usr/local/lib/python3.10/dist-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.5)\n",
            "Requirement already satisfied: Werkzeug<3.1 in /usr/local/lib/python3.10/dist-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (3.0.2)\n",
            "Collecting dash-html-components==2.0.0 (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret)\n",
            "  Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)\n",
            "Collecting dash-core-components==2.0.0 (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret)\n",
            "  Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)\n",
            "Collecting dash-table==5.0.0 (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret)\n",
            "  Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)\n",
            "Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.10/dist-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (4.11.0)\n",
            "Collecting retrying (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret)\n",
            "  Downloading retrying-1.3.4-py3-none-any.whl (11 kB)\n",
            "Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.10/dist-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (1.6.0)\n",
            "Requirement already satisfied: jupyter-client in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (6.1.12)\n",
            "Requirement already satisfied: tornado>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (6.3.3)\n",
            "Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=5.5.0->pycaret) (0.8.4)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (23.2.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (2023.12.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.35.0)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.18.0)\n",
            "Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=4.2.0->pycaret) (4.2.1)\n",
            "Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=5.5.0->pycaret) (0.7.0)\n",
            "Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.5.0->pycaret) (0.2.13)\n",
            "Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.10/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (6.5.5)\n",
            "Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.10/dist-packages (from Flask<3.1,>=1.0.4->dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.0)\n",
            "Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.10/dist-packages (from Flask<3.1,>=1.0.4->dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (8.1.7)\n",
            "Requirement already satisfied: pyzmq<25,>=17 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (24.0.1)\n",
            "Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (23.1.0)\n",
            "Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (6.5.4)\n",
            "Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.8.3)\n",
            "Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.18.1)\n",
            "Requirement already satisfied: prometheus-client in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.20.0)\n",
            "Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.0.0)\n",
            "Requirement already satisfied: jupyter-server>=1.8 in /usr/local/lib/python3.10/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.24.0)\n",
            "Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.10/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.2.4)\n",
            "Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (4.9.4)\n",
            "Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (4.12.3)\n",
            "Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (6.1.0)\n",
            "Requirement already satisfied: defusedxml in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.7.1)\n",
            "Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.4)\n",
            "Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.3.0)\n",
            "Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.8.4)\n",
            "Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.10.0)\n",
            "Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.5.1)\n",
            "Requirement already satisfied: tinycss2 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.3.0)\n",
            "Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.10/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (21.2.0)\n",
            "Requirement already satisfied: anyio<4,>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (3.7.1)\n",
            "Requirement already satisfied: websocket-client in /usr/local/lib/python3.10/dist-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.8.0)\n",
            "Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.16.0)\n",
            "Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (2.5)\n",
            "Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (0.5.1)\n",
            "Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<4,>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.3.1)\n",
            "Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<4,>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (1.2.1)\n",
            "Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret) (2.22)\n",
            "Building wheels for collected packages: pyod\n",
            "  Building wheel for pyod (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for pyod: filename=pyod-1.1.3-py3-none-any.whl size=190250 sha256=60aea20a7227557f0eb158bd2687c45effd85ec7a5bfbca9f72a38aea3b09e63\n",
            "  Stored in directory: /root/.cache/pip/wheels/05/f8/db/124d43bec122d6ec0ab3713fadfe25ebed8af52ec561682b4e\n",
            "Successfully built pyod\n",
            "Installing collected packages: kaleido, dash-table, dash-html-components, dash-core-components, xxhash, wurlitzer, tsdownsample, scikit-base, schemdraw, retrying, orjson, joblib, jedi, deprecation, scikit-learn, sktime, scikit-plot, pyod, imbalanced-learn, dash, pmdarima, plotly-resampler, category-encoders, tbats, pycaret\n",
            "  Attempting uninstall: joblib\n",
            "    Found existing installation: joblib 1.4.0\n",
            "    Uninstalling joblib-1.4.0:\n",
            "      Successfully uninstalled joblib-1.4.0\n",
            "  Attempting uninstall: scikit-learn\n",
            "    Found existing installation: scikit-learn 1.2.2\n",
            "    Uninstalling scikit-learn-1.2.2:\n",
            "      Successfully uninstalled scikit-learn-1.2.2\n",
            "  Attempting uninstall: imbalanced-learn\n",
            "    Found existing installation: imbalanced-learn 0.10.1\n",
            "    Uninstalling imbalanced-learn-0.10.1:\n",
            "      Successfully uninstalled imbalanced-learn-0.10.1\n",
            "Successfully installed category-encoders-2.6.3 dash-2.17.0 dash-core-components-2.0.0 dash-html-components-2.0.0 dash-table-5.0.0 deprecation-2.1.0 imbalanced-learn-0.12.2 jedi-0.19.1 joblib-1.3.2 kaleido-0.2.1 orjson-3.10.3 plotly-resampler-0.10.0 pmdarima-2.0.4 pycaret-3.3.2 pyod-1.1.3 retrying-1.3.4 schemdraw-0.15 scikit-base-0.7.7 scikit-learn-1.4.2 scikit-plot-0.3.7 sktime-0.26.0 tbats-1.1.3 tsdownsample-0.1.3 wurlitzer-3.1.0 xxhash-3.4.1\n"
          ]
        }
      ],
      "source": [
        "!pip install pycaret"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "oBM_1gcTmWbW",
        "outputId": "97c2d281-1405-404f-f584-80e795de7c1d"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Writing app.py\n"
          ]
        }
      ],
      "source": [
        "%%writefile app.py"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "XbTab5hMmeVN",
        "outputId": "04f18837-41e5-4e3b-d28a-8b0e864343e1"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "34.148.200.124\n"
          ]
        }
      ],
      "source": [
        "! wget -q -O - ipv4.icanhazip.com"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 9,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "FQllcRGoVsAt",
        "outputId": "bc45916a-b388-44b7-f271-4a2d76145171"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.\n",
            "\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[34m\u001b[1m  You can now view your Streamlit app in your browser.\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[34m  Network URL: \u001b[0m\u001b[1mhttp://172.28.0.12:8501\u001b[0m\n",
            "\u001b[34m  External URL: \u001b[0m\u001b[1mhttp://34.148.200.124:8501\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[K\u001b[?25hnpx: installed 22 in 2.797s\n",
            "your url is: https://nice-chairs-hunt.loca.lt\n",
            "2024-05-07 05:02:04.854 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 05:02:04.876 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 05:02:04.879 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 200, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 161, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 05:05:24.008 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 05:05:24.025 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 05:05:24.029 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 200, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 161, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 05:05:27.856 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 05:05:27.871 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 05:05:27.874 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 200, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 161, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 05:05:41.456 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 05:05:41.472 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 05:05:41.475 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 200, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 161, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 05:07:00.088 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 05:07:00.102 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 200, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 159, in main\n",
            "    drop_duplicates(dataframe,dataframe)\n",
            "TypeError: drop_duplicates() takes 1 positional argument but 2 were given\n",
            "2024-05-07 05:07:17.691 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 05:07:17.714 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 05:07:17.717 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 200, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 161, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 06:07:28.305 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:07:28.320 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:07:28.323 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 200, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 161, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 06:14:08.886 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:14:08.903 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 200, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 159, in main\n",
            "    drop_duplicates(dataframe)\n",
            "  File \"/content/app.py\", line 88, in drop_duplicates\n",
            "    drop_duplicates_option = st.radio(\"Drop duplicate rows?\", key=\"drop_duplicates_checkbox\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "TypeError: RadioMixin.radio() missing 1 required positional argument: 'options'\n",
            "2024-05-07 06:15:19.627 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:15:19.638 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 200, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 159, in main\n",
            "    drop_duplicates(dataframe)\n",
            "  File \"/content/app.py\", line 88, in drop_duplicates\n",
            "    drop_duplicates_option = st.radio(\"Drop duplicate rows?\", key=\"drop_duplicates_checkbox\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "TypeError: RadioMixin.radio() missing 1 required positional argument: 'options'\n",
            "2024-05-07 06:16:42.709 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:16:42.737 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:16:42.739 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 200, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 161, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 06:16:55.044 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:16:55.066 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:16:55.069 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 200, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 161, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 06:18:43.749 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:18:43.768 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:18:43.770 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 200, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 161, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 06:19:09.586 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:19:09.601 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:19:09.604 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 201, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 162, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 06:19:17.069 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:19:17.086 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:19:17.089 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 201, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 162, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 06:20:23.849 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:20:23.864 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:20:23.867 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 190, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 151, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 06:20:28.526 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:20:28.542 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:20:28.545 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 190, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 151, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 06:20:38.806 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:20:38.819 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:20:38.822 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 190, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 151, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 06:20:42.199 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:20:42.213 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:20:42.215 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 190, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 151, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 06:21:20.913 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:21:20.926 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('float64') with type numpy.dtypes.Float64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:21:20.929 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 600, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/app.py\", line 190, in <module>\n",
            "    main()\n",
            "  File \"/content/app.py\", line 151, in main\n",
            "    perform_eda(dataframe)\n",
            "  File \"/content/app.py\", line 22, in perform_eda\n",
            "    analyze_data = st.checkbox(\"Perform EDA?\")\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 148, in checkbox\n",
            "    return self._checkbox(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/checkbox.py\", line 319, in _checkbox\n",
            "    checkbox_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 164, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 209, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.checkbox`.\n",
            "2024-05-07 06:21:54.390 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:23:40.771 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:23:51.887 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:24:03.921 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:24:07.764 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:24:09.284 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:24:26.851 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:24:38.585 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:24:39.035 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:24:39.297 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "2024-05-07 06:24:42.659 Serialization of dataframe to Arrow table was unsuccessful due to: (\"Could not convert dtype('int64') with type numpy.dtypes.Int64DType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column 0 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
            "                    Description             Value\n",
            "0                    Session id               123\n",
            "1                        Target         Purchased\n",
            "2                   Target type        Regression\n",
            "3           Original data shape          (400, 4)\n",
            "4        Transformed data shape          (400, 4)\n",
            "5   Transformed train set shape          (280, 4)\n",
            "6    Transformed test set shape          (120, 4)\n",
            "7              Numeric features                 3\n",
            "8                    Preprocess              True\n",
            "9               Imputation type            simple\n",
            "10           Numeric imputation              mean\n",
            "11       Categorical imputation              mode\n",
            "12               Fold Generator             KFold\n",
            "13                  Fold Number                10\n",
            "14                     CPU Jobs                -1\n",
            "15                      Use GPU             False\n",
            "16               Log Experiment             False\n",
            "17              Experiment Name  reg-default-name\n",
            "18                          USI              295e\n",
            "Processing:  26% 21/81 [00:11<00:15,  3.93it/s]\n",
            "Processing:   0% 0/81 [00:00<?, ?it/s]\u001b[A\n",
            "Processing:   6% 5/81 [00:00<00:07,  9.60it/s]\u001b[A^C\n"
          ]
        }
      ],
      "source": [
        "! streamlit run app.py & npx localtunnel --port 8501"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#the code not run here This is for display only\n",
        "import streamlit as st\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import seaborn as sns\n",
        "import matplotlib.pyplot as plt\n",
        "from sklearn.impute import SimpleImputer\n",
        "from sklearn.preprocessing import MinMaxScaler, StandardScaler\n",
        "from sklearn.preprocessing import LabelEncoder\n",
        "from pycaret.regression import RegressionExperiment\n",
        "from pycaret.classification import ClassificationExperiment\n",
        "\n",
        "def perform_eda(dataframe):\n",
        "  st.header(\"Exploratory Data Analysis (EDA):-\")\n",
        "\n",
        "  st.subheader(\"Data Shape\")\n",
        "  st.write(f\"The dataset has {dataframe.shape[0]} rows and {dataframe.shape[1]} columns.\")\n",
        "\n",
        "  st.subheader(\"Data Types\")\n",
        "  st.write(dataframe.dtypes)\n",
        "\n",
        "  analyze_data = st.checkbox(\"Perform EDA?\")\n",
        "  if analyze_data:\n",
        "    visualiz_columns = st.multiselect(\"Select the columns for visualization:\", options=dataframe.columns)\n",
        "    if visualiz_columns:\n",
        "      numeric_columns = dataframe[visualiz_columns].select_dtypes(include=['number']).columns\n",
        "      st.subheader(\"Histograms\")\n",
        "      for column in numeric_columns:\n",
        "        plt.figure(figsize=(8, 4))\n",
        "        sns.histplot(data=dataframe, x=column, kde=True)\n",
        "        plt.title(f\"Histogram For numerical data - {column}\")\n",
        "        plt.xlabel(column)\n",
        "        plt.ylabel(\"Frequency of values\")\n",
        "        plt.show()\n",
        "        st.pyplot()\n",
        "      st.subheader(\"boxplot\")\n",
        "      for column in numeric_columns:\n",
        "        plt.figure(figsize=(8, 4))\n",
        "        sns.boxplot(data=dataframe, y=column)\n",
        "        plt.title(f\"Box Plot For numerical data - {column}\")\n",
        "        plt.ylabel(column)\n",
        "        plt.show()\n",
        "        st.pyplot()\n",
        "      st.subheader(\"scatterplot\")\n",
        "      if len(numeric_columns) >= 2:\n",
        "        for i in range(len(numeric_columns)):\n",
        "          for j in range(i + 1, len(numeric_columns)):\n",
        "            plt.figure(figsize=(8, 6))\n",
        "            sns.scatterplot(data=dataframe, x=numeric_columns[i], y=numeric_columns[j])\n",
        "            plt.title(f\"Scatter Plot VS {numeric_columns[i]} and {numeric_columns[j]}\")\n",
        "            plt.xlabel(numeric_columns[i])\n",
        "            plt.ylabel(numeric_columns[j])\n",
        "            plt.show()\n",
        "            st.pyplot()\n",
        "      st.subheader(\"correlation_matrix\")\n",
        "      if len(numeric_columns) >= 2:\n",
        "        correlation_matrix = dataframe[visualiz_columns].corr()\n",
        "        plt.figure(figsize=(10, 8))\n",
        "        sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\n",
        "        plt.title(\"Heatmap For correlation coefficients between numerical features\")\n",
        "        plt.show()\n",
        "        st.pyplot()\n",
        "\n",
        "def encode_categorical(dataframe):\n",
        "    categorical_features = dataframe.select_dtypes(include=['object']).columns\n",
        "    encoding_method = st.radio(\"Select encoding method for categorical data:\", (\"Label Encoding\", \"One-Hot Encoding\"))\n",
        "    if encoding_method == \"Label Encoding\":\n",
        "        for col in categorical_features:\n",
        "            dataframe[col] = LabelEncoder().fit_transform(dataframe[col])\n",
        "\n",
        "def drop_duplicates(dataframe):\n",
        "    st.header(\"select Drop duplicate rows?\")\n",
        "    drop_duplicates_option = st.checkbox(\"Drop duplicate\", key=\"drop_duplicates_checkbox\")\n",
        "\n",
        "    if drop_duplicates_option:\n",
        "        dataframe.drop_duplicates(inplace=True)\n",
        "\n",
        "    return dataframe\n",
        "\n",
        "\n",
        "def normalize(dataframe):\n",
        "    numerical_features = dataframe.select_dtypes(include=['number']).columns\n",
        "    normalization_method = st.radio(\"Select normalization method:\", (\"Min-Max Scaling\", \"Standard Scaling\"))\n",
        "\n",
        "    if normalization_method == \"Min-Max Scaling\":\n",
        "        scaler = MinMaxScaler()\n",
        "        dataframe[numerical_features] = scaler.fit_transform(dataframe[numerical_features])\n",
        "\n",
        "    elif normalization_method == \"Standard Scaling\":\n",
        "        scaler = StandardScaler()\n",
        "        dataframe[numerical_features] = scaler.fit_transform(dataframe[numerical_features])\n",
        "\n",
        "    return dataframe\n",
        "\n",
        "def choose_variables(dataframe):\n",
        "    st.header(\"Choose X and Y variables\")\n",
        "    X_variables = st.multiselect(\"Select independent variables (X):\", options=dataframe.columns)\n",
        "    Y_variable = st.selectbox(\"Select dependent variable (Y):\", options=dataframe.columns)\n",
        "    return X_variables, Y_variable\n",
        "\n",
        "def main():\n",
        "  with st.sidebar:\n",
        "    st.header(\"The steps to prediction accuracy:-\")\n",
        "    st.text(\"1- upload csv file or excel file \")\n",
        "    st.text(\"2- choose target feature\")\n",
        "    st.text(\"3- some perform eda\")\n",
        "    st.text(\"4- handle missing values\")\n",
        "    st.text(\"5- drop_duplicates\")\n",
        "    st.text(\"6- choose x and y \")\n",
        "    st.text(\"7- encode categorical data \")\n",
        "    st.text(\"8- data normalizetion \")\n",
        "    st.text(\"9- using pycaret\")\n",
        "\n",
        "  dataframe = pd.DataFrame()\n",
        "  target = \"\"\n",
        "\n",
        "\n",
        "  data = st.file_uploader(\"upload the file:-\", type=['csv', 'xslx','json'])\n",
        "  if data is not None:\n",
        "\n",
        "    if \"csv\" in data.name:\n",
        "      dataframe = pd.read_csv(data)\n",
        "    elif \"json\" in data.name:\n",
        "      dataframe = pd.read_json(data)\n",
        "    elif \"excel\" in data.name:\n",
        "      dataframe = pd.read_excel(data)\n",
        "    else:\n",
        "      raise ValueError(\"Unsupported file format\")\n",
        "\n",
        "    st.write(dataframe.head())\n",
        "\n",
        "    target = st.selectbox(\"choose The target:-\", dataframe.columns)\n",
        "\n",
        "  if not dataframe.empty:\n",
        "\n",
        "    perform_eda(dataframe)\n",
        "\n",
        "\n",
        "    select_columns = st.multiselect(\"Select features to remove from the dataset:\", options=dataframe.columns)\n",
        "    if select_columns:\n",
        "      dataframe.drop(select_columns, axis=1, inplace=True)\n",
        "\n",
        "\n",
        "    numerical_features = dataframe.select_dtypes(['int64', 'float64']).columns\n",
        "    categorical_feature = dataframe.select_dtypes(['object']).columns\n",
        "    missing_value_num = st.radio(\"Set missing value for numerical value \", [\"mean\", \"median\"])\n",
        "    missing_value_cat = st.radio(\"Set missing value for categorical value \", ['most frequent', \"put additional class\"])\n",
        "\n",
        "    for col in numerical_features:\n",
        "      dataframe[col] = SimpleImputer(strategy=missing_value_num, missing_values=np.nan).fit_transform(\n",
        "              dataframe[col].values.reshape(-1, 1))\n",
        "    for col in categorical_feature:\n",
        "      if dataframe[col].nunique() > 7:\n",
        "        dataframe[col] = SimpleImputer(strategy='most_frequent', missing_values=np.nan).fit_transform(\n",
        "                    dataframe[col].values.reshape(-1, 1))\n",
        "    else:\n",
        "      dataframe[col] = LabelEncoder().fit_transform(dataframe[col])\n",
        "\n",
        "    drop_duplicates(dataframe)\n",
        "\n",
        "    X_variables, Y_variable = choose_variables(dataframe)\n",
        "\n",
        "    encode_categorical(dataframe)\n",
        "\n",
        "    #normalize(dataframe)\n",
        "\n",
        "    if (len(numerical_features) != 0):\n",
        "      st.header(\"Numerical Columns\")\n",
        "      st.write(numerical_features)\n",
        "    if (len(categorical_feature) != 0):\n",
        "      st.header(\"Categorical columns\")\n",
        "      st.write(categorical_feature)\n",
        "    if (len(categorical_feature) != 0 or len(numerical_features) != 0):\n",
        "      st.header(\"Number of null values\")\n",
        "      st.write(dataframe.isna().sum())\n",
        "\n",
        "\n",
        "    if target and X_variables and Y_variable:\n",
        "\n",
        "      option = \"Regression\" if dataframe[Y_variable].dtype in ['int64', 'float64'] else \"Classification\"\n",
        "      st.header(f\"Detected Task Type: {option}\")\n",
        "\n",
        "      if option == 'Regression':\n",
        "        s = RegressionExperiment()\n",
        "      elif option == 'Classification':\n",
        "       s = ClassificationExperiment()\n",
        "\n",
        "      s.setup(dataframe, target=Y_variable, session_id=123)\n",
        "      best = s.compare_models()\n",
        "      st.header(\"Best Algorithm\")\n",
        "      st.write(best)\n",
        "      st.write(s.evaluate_model(best))\n",
        "      st.header(\"20 rows of Prediction\")\n",
        "      predictions = s.predict_model(best, data=dataframe)\n",
        "      st.write(predictions.head(20))\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "  main()"
      ],
      "metadata": {
        "id": "SEJjYhG62NG_"
      },
      "execution_count": 18,
      "outputs": []
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMwjPNmEIx273Zvy4a2Yv53",
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}